### ISSUE TITLE
No matching distribution found for pkg-resources==0.0.0

### ISSUE THREAD

**Issue by rdmurphy** [propublica/django-collaborative#1]
👋  Hello!

Was trying to get this cool thing running locally and hit a small snag — `pkg-resources==0.0.0` appears in the `requirements.txt` but doesn't appear to be install-able. I tried to run `pip install pkg-resources` separately and it didn't take either.

**Comment by brandonrobertz** [comment]
Pull latest and re-run your `pip install -r requirements.txt`
This was an oddity from my local 3.7 pip freeze.

**Comment by rdmurphy** [comment]
That worked — I'm in. Thanks!
