### ISSUE TITLE
Column sort doesn't recognize lowercase words

### ISSUE THREAD

**Issue by rachelgli** [propublica/django-collaborative#21]
When you sort a column A-Z, it doesn't alphabetize words that begin with a lowercase letter. So all of the lowercase words are put at the end of the list, and not alphabetized with the full list.

**Comment by brandonrobertz** [comment]
Fixed in https://github.com/propublica/django-collaborative/commit/c81c837c5a3e3cce9148378ab9c59fc77516191c
All fields are now case-insensitive by default (which is what most users will expect).
