### ISSUE TITLE
Tags are repeating in the filter list

### ISSUE THREAD

**Issue by rachelgli** [propublica/django-collaborative#22]
This might be solved by the changes you're making to tags, but just flagging.
<img width="264" alt="Screen Shot 2019-07-29 at 12 07 11 PM" src="https://user-images.githubusercontent.com/42387717/62064204-548d5680-b1fa-11e9-8c8d-01db3a31b119.png">

**Comment by brandonrobertz** [comment]
Fixed in https://github.com/propublica/django-collaborative/commit/c440a8c33055ed7ad0958941020925dfdd9f7332
