### ISSUE TITLE
Field-level redaction using Google's AI toolkit

### ISSUE THREAD

**Issue by rachelgli** [propublica/django-collaborative#25]

**Comment by brandonrobertz** [comment]
This is in as of https://github.com/propublica/django-collaborative/commit/be0b652d00ce8d30f9e9205a3d2bd474d425b5ba

We have some instructions in the `settings.py` file. All you need to do is uncomment some stuff in the new data pipeline, plug in the Google credentials and add "-PII" to the header of any column you want redacted.
