### ISSUE TITLE
Private spreadsheet workaround

### ISSUE THREAD

**Issue by rachelgli** [propublica/django-collaborative#31]
Can be using this: https://developers.google.com/docs/api/quickstart/python

**Comment by brandonrobertz** [comment]
Implemented in https://github.com/propublica/django-collaborative/commit/d959c05570ca2f6e32d7ba78a748c5fbe7f3d267
Docs are both in the app (as a modal) and the source markdown is here: https://github.com/propublica/django-collaborative/blob/master/docs/google-private-sheets-setup.md
