### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by schwanksta** [propublica/django-collaborative#32]
We need to flesh out not just the README, but write actual documentation about how the system works and how people can use it. Assigning this to all of us.

**Comment by schwanksta** [comment]
https://docs.google.com/document/d/19IF59O6XA53izJdQREHplM50aO6mr_k2ST1rhpZVrOU/edit?ts=5d572133

**Comment by brandonrobertz** [comment]
I started putting some source markdown docs in the source (will import them, probably as condensed versions? into the document above). Just wanted to catalog them here as I did them.

Private sheets setup instructions: https://github.com/propublica/django-collaborative/blob/master/docs/google-private-sheets-setup.md
