### ISSUE TITLE
Tags shouldn't appear under the Users or Groups pages

### ISSUE THREAD

**Issue by rachelgli** [propublica/django-collaborative#35]
![Screen Shot 2019-08-23 at 11 20 09 AM](https://user-images.githubusercontent.com/42387717/63603615-fd2f9b80-c597-11e9-86e3-19417b3c9cd7.png)

**Comment by brandonrobertz** [comment]
Fixed as of https://github.com/propublica/django-collaborative/commit/c21634adf4f00e6408e7a48bf0f5dfe5a65d6ea8
