### ISSUE TITLE
Turn DEBUG=False

### ISSUE THREAD

**Issue by schwanksta** [propublica/django-collaborative#36]
September 12

**Comment by brandonrobertz** [comment]
also, we should reduce logging for the `collaborative` and `django_models_from_csv` apps in `settings.py`. They're set to debug, which is super verbose.

**Comment by brandonrobertz** [comment]
Disabled DEBUG, reduced logging. https://github.com/propublica/django-collaborative/commit/5398cf2b1de13b1d4a118fbe4bf7a323a6cf4088

**Comment by brandonrobertz** [comment]
Had to bring DEBUG=True back. It breaks templates for some reason.

**Comment by brandonrobertz** [comment]
Okay! Fixed the static file issue with DEBUG=False, now it's re-instated.

**Comment by tommeagher** [comment]
Hi! It looks like you still have DEBUG=True in production: 
https://github.com/propublica/django-collaborative/blob/master/collaborative/settings.py#L31

**Comment by brandonrobertz** [comment]
Yikes! Good catch. I'll do some testing later with `DEBUG=False` and then push a fix. Re-opening.

**Comment by brandonrobertz** [comment]
Okay, I've pushed up the default `DEBUG=False`. I've tested a bunch with this and I'm confident the old issues with it (due to whitenoise) no longer are problems.

If someone finds otherwise, let me know and I'll re-open this.
