### ISSUE TITLE
Screendoor project wouldn't load

### ISSUE THREAD

**Issue by rachelgli** [propublica/django-collaborative#38]
![Screen Shot 2019-08-27 at 2 12 55 PM](https://user-images.githubusercontent.com/42387717/63796967-122c6780-c8d5-11e9-8387-46e7f64123a1.png)

When I gave it the name DocHateSignUps it wouldn't upload, and I got this error. When I gave it an all lowercase name, it loaded correctly.

**Comment by brandonrobertz** [comment]
Fixed (and deployed) in https://github.com/propublica/django-collaborative/commit/f0264341fada90a41c34f49751a78a58bb43dde9

I did some additional testing using Screendoor and things seem to be working.
