### ISSUE TITLE
Formatting on main page when no files uploaded

### ISSUE THREAD

**Issue by rachelgli** [propublica/django-collaborative#39]
![Screen Shot 2019-09-04 at 11 55 21 AM](https://user-images.githubusercontent.com/42387717/64271211-ed567680-cf0a-11e9-8159-15b3a8f2452b.png)

When you launch the app in Heroku, there's some formatting issues if you don't upload a file.

**Comment by brandonrobertz** [comment]
Fixed. Now we show a message when there are no imports: "No data sources added. Import one here." https://github.com/propublica/django-collaborative/commit/f523fb7b0a29331f4b1e8fd744bf31e841c3634e
