### ISSUE TITLE
Project not pulling in date field from Screendoor

### ISSUE THREAD

**Issue by rachelgli** [propublica/django-collaborative#43]
![Screen Shot 2019-09-05 at 2 27 50 PM](https://user-images.githubusercontent.com/42387717/64368991-63c9a600-cfe9-11e9-847d-2acc8d318e36.png)
I tried reimporting it and marking it as a date only field. It's still not showing up.

**Comment by brandonrobertz** [comment]
Screendoor dates now get parsed. I don't have a screendoor test case that I can use locally, so I've been going off the remote server not failing to parse them.

**Comment by brandonrobertz** [comment]
Cool! I verified it's working. I also added handlers for the remaining screendoor data types (location, other checked w/o response)
