### ISSUE TITLE
Meta data isn't automatically showing on Heroku-built project

### ISSUE THREAD

**Issue by rachelgli** [propublica/django-collaborative#46]
![Screen Shot 2019-09-09 at 9 38 42 AM](https://user-images.githubusercontent.com/42387717/64535662-ab9c4600-d2e5-11e9-808f-88f8968e7f71.png)
It makes me click to open to add meta data.

**Comment by rachelgli** [comment]
Also, status and assigned to aren't working in the main view.
![Screen Shot 2019-09-09 at 9 48 44 AM](https://user-images.githubusercontent.com/42387717/64536405-0e421180-d2e7-11e9-8134-40b79cb7c587.png)

**Comment by rachelgli** [comment]
If I add meta data, it then duplicates the meta data section.
![Screen Shot 2019-09-09 at 10 01 57 AM](https://user-images.githubusercontent.com/42387717/64537495-e9e73480-d2e8-11e9-9357-4b48b7cb69bf.png)

**Comment by rachelgli** [comment]
And this happens in the list view.
![Screen Shot 2019-09-09 at 10 02 52 AM](https://user-images.githubusercontent.com/42387717/64537542-05523f80-d2e9-11e9-8a25-7699439ec5a7.png)

**Comment by brandonrobertz** [comment]
this is now fixed. i've tested with the failing spreadsheet and deployed Heroku multiple times to ensure success is consistent.
