### ISSUE TITLE
Refresh data won't work on Heroku-launched project

### ISSUE THREAD

**Issue by rachelgli** [propublica/django-collaborative#47]
![Screen Shot 2019-09-09 at 11 00 53 AM](https://user-images.githubusercontent.com/42387717/64542231-3171be80-d2f1-11e9-8aba-485a50a293f5.png)
I tried switching it to text only but it didn't work.

**Comment by brandonrobertz** [comment]
This is fixed. Numbers now get parsed from common formats (money, commas, etc).
