### ISSUE TITLE
Screendoor data import failure

### ISSUE THREAD

**Issue by rachelgli** [propublica/django-collaborative#5]
For a different Screendoor form, I got through all the steps until the final import step, when I got the same error message for every row.
![Screen Shot 2019-06-06 at 5 05 36 PM](https://user-images.githubusercontent.com/42387717/59066593-6a773e80-887d-11e9-9e30-332f739392b5.png)

**Comment by brandonrobertz** [comment]
Fixed. Added the screendoor internal API response ID as the row ID.
