### ISSUE TITLE
No Google authentication on main page for fresh install

### ISSUE THREAD

**Issue by stucka** [propublica/django-collaborative#50]
Per @rachelgli , I'm filing this ticket:

I've got a fairly fresh install of Collaborate running on Heroku. So fresh it has no data, which may be part of the problem. But the base page at / does not have a way to authenticate with Google:
![basepage](https://user-images.githubusercontent.com/533487/66082501-44666000-e538-11e9-8bb9-31108c105870.png)

Clicking on the Collaborate icon leads to /admin/ , which redirects to /admin/login/?next=/admin/ , where I do get Google authentication:
![adminpage](https://user-images.githubusercontent.com/533487/66082642-90190980-e538-11e9-9559-f325a80d3f0f.png)

If this is your biggest problem you're in really good shape.

**Comment by brandonrobertz** [comment]
For the initial load (before you've gone through the Google Credentials page) you can't do Google Sign In, so we hide it. Once you've completed the Google Credentials page and added the OAuth keys, then users who visit `/admin/` should see that "Sign in with Google" button.

So my question is: have you entered credentials? Once you've imported and refined your initial dataset, you should be moved to the page. Otherwise it's here: `/setup-credentials/`

Let me know if anything isn't working from there.

**Comment by stucka** [comment]
@brandonrobertz Thanks! I've got credentials loaded in and they work through the /admin/ login, but I don't get a Google credentials login on just / ...

**Comment by brandonrobertz** [comment]
Yeah sorry, I misspoke. On the main landing page (`/`) users will see the Google Sign In. `/admin` is for logging in. As long as users hit the landing page, they should see the correct thing.

Does that cover it?

**Comment by stucka** [comment]
Yeah, that's what I'm saying -- see my first screenshot. There's a race condition in which you can set up Google auth and add users but not have added data yet. In that case, people visiting / don't get the Google auth option.

Granted, that initial workflow may make no sense to anybody, and that whole nothing can be foolproof thing comes to mind ..

**Comment by brandonrobertz** [comment]
The flow is really set up for people to configure it like this:
1. Go to the main page, log in with their initial user and pass
2. Import an initial dataset (complete begin and refine pages)
3. Complete the Google Credentials page, completing the OAuth section and whitelists
4. Give people your URL and have them get working.

I should probably just hide Google Sign In all together from all pages (will need to override the admin views) if there's no OAuth credentials.

**Comment by brandonrobertz** [comment]
All right, I've hidden the Google Sign In button from the login screens if no OAuth credentials have been stored. This is in master now: https://github.com/propublica/django-collaborative/commit/26f703cb7d2f08e6f724a478c7272d80e5063e41 Closing this out.
