### ISSUE TITLE
Google Oauth2 throws an error with http per docs

### ISSUE THREAD

**Issue by tommeagher** [propublica/django-collaborative#51]
Hi, was just setting up Collaborate @themarshallproject and hit one hiccup following the directions on the setup-credentials page. I think on this line: https://github.com/propublica/django-collaborative/blob/master/templates/setup-credentials.html#L108

When I changed it from http to https, my users were able to authenticate through Google. Following the directions on the page, my users got this msg: 
<img width="726" alt="screen_shot_2019-10-10_at_3 35 56_pm" src="https://user-images.githubusercontent.com/713778/66601397-cc221f00-eb75-11e9-8285-591a8b1e2317.png">

Hope this helps. Thanks for open sourcing this!

**Comment by brandonrobertz** [comment]
Thanks for reporting this. I pushed the `HTTPS` fix to the `master` branch.

**Comment by tommeagher** [comment]
cool. thank you for open sourcing it!
