### ISSUE TITLE
User permissions aren't working properly

### ISSUE THREAD

**Issue by rachelgli** [propublica/django-collaborative#52]
![Screen Shot 2019-10-30 at 3 00 26 PM](https://user-images.githubusercontent.com/42387717/67889884-099b1c00-fb26-11e9-85f7-1c8378915227.png)

Unless you check the superuser box, users can't see any projects. Adding groups/user permissions don't work. Once you check the superuser box, the user can access all the projects.

**Comment by brandonrobertz** [comment]
I thought this used to work (it did, right?), so I'll figure out what caused this to break.

**Comment by brandonrobertz** [comment]
Okay, I went through this and I think I fixed the issue. I tested with a new user a granted single permission (and removed it) and everything seems like it's working how it should.

Fixing commit: https://github.com/propublica/django-collaborative/commit/3e2c1fde0f5177b3e181b05ecc264a314fe2392f

Let me know if deploying the latest `master` branch works for you.

**Comment by rachelgli** [comment]
This works!! Thanks so much Brandon.
