### ISSUE TITLE
Data sources appearing multiple times

### ISSUE THREAD

**Issue by BluClare** [propublica/django-collaborative#53]
When I am on the home screen, my data source is appearing multiple times. It is a Screendoor dataset. 
![home screen error](https://user-images.githubusercontent.com/18301380/67919612-2f432680-fbf5-11e9-8577-6c93e8d3b67b.JPG)

**Comment by brandonrobertz** [comment]
Do you have the latest version of the code? This was a problem I recently fixed, but I wasn't able to test Screendoor. A temporary fix (in case there's a new issue) is usually restarting the app, FYI.

Let me know and thanks for using Collaborate!

**Comment by brandonrobertz** [comment]
Did you have any success since pulling latest `master` branch? The fix for the issue I was aware of went in on Oct 8, 2019. If you pulled after that, let me know and I can investigate further.

**Comment by BluClare** [comment]
Hi Brandon, yes that fixed the problem. Thank you. I'll close this issue.
