### ISSUE TITLE
Data refresh isn't working with Screendoor data

### ISSUE THREAD

**Issue by rachelgli** [propublica/django-collaborative#54]
On our local version, one of the live Screendoor projects isn't updating dynamically. I had to do a hard refresh through Re-import.

**Comment by brandonrobertz** [comment]
Heroku is the only platform that we can automatically update on. If it's not a Heroku install, developers need to add a cron job that does the updating. I have an example cron line that people can use:

https://github.com/propublica/django-collaborative/blob/master/deploy/cron/refresh_data_sources

It assumes Collaborate is installed at `/opt/collaborative/app` and python virtual env at `/opt/collaborative/venv`. They would basically just need to add the above file to `/etc/crontab`.

**Comment by rachelgli** [comment]
Ok. I'm going to update this in the user manual. Also CC @schwanksta for when we set up the shared version.
