### ISSUE TITLE
Collaborate is not importing name and email from Screendoor

### ISSUE THREAD

**Issue by BluClare** [propublica/django-collaborative#55]
Hi,

I have a project which is pulling data from Screendoor, but for some reason the names and email addresses are not coming through to the Collaborate portal (these are compulsory data fields in Screendoor). 

Is there something I'm missing?

**Comment by rachelgli** [comment]
I identified this problem as well and spoke to Brandon about it but I hadn't logged it here yet. This is definitely something we need to fix. Thanks Clare!

**Comment by brandonrobertz** [comment]
I'm gonna look at this soon (sorry, missed this ticket in my last sweep). Just to be clear, Rachel and I are under the impression that fields with default values aren't getting their default values picked up.

If it's something other than this, I can look further, but I might need more information (like, some error logs from when you import the Screendoor data).

**Comment by BluClare** [comment]
Thanks Brandon and Rachel,

Yes, you are correct. The fields with default values aren't getting their default values picked up - it's just Name and Email. They're the details that Screendoor uses for users to log back into their form draft, but it doesn't make sense for us to have that entry twice. 

There were error logs when I imported my project Screendoor, but I don't have a record currently, and the rest of the imported fields are working.

**Comment by brandonrobertz** [comment]
I just pushed up a fix for this (commit: https://github.com/propublica/django-collaborative/commit/9e8eb607a36a00289050f015dc610e54f315122c). I tested it against one of the ProPublica Screendoor forms and everything looks good to me. Let me know if things look okay on your end after you've pulled latest.

**Comment by rachelgli** [comment]
Hi Brandon, this issue is fixed, which is great! However, when I successfully imported the project, meta data has now disappeared. I'm going to give you access to project so you can see what's up.
![Screen Shot 2019-12-03 at 11 53 21 AM](https://user-images.githubusercontent.com/42387717/70071570-8e64d400-15c3-11ea-9dca-8bdf99fca86c.png)

**Comment by rachelgli** [comment]
![Screen Shot 2019-12-03 at 11 55 04 AM](https://user-images.githubusercontent.com/42387717/70071729-c409bd00-15c3-11ea-9238-5b3458766c58.png)
An example of one that had been uploaded previously

**Comment by brandonrobertz** [comment]
Okay! The root of the problem is a breaking change in Django 2.2.8 that was pushed to fix a potential security problem in Django. **Collaborate is not vulnerable to this attack.** For now, we're forced to use 2.2.7 as getting the old functionality is going to be complicated.
