### ISSUE TITLE
Getting server error 500 when uploading Screendoor project

### ISSUE THREAD

**Issue by riogringa** [propublica/django-collaborative#58]
I get a server error 500 error when trying to upload a new project from Screendoor. It has numerous responses, and there are no duplicate columns. I tested this on our external Collaborate and on your server, and I'm getting the same result. So I'm not sure why it's not working. This happened with another Screendoor project in December and I couldn't figure out the cause of the error. (For later reference: it's the Oregon timber callout)

I'm hoping we can get you into Screendoor to look in there to see what the issue might be.

**Comment by BluClare** [comment]
This is also happening to us in Australia.

**Comment by brandonrobertz** [comment]
Closing this as it appears to be the same as https://github.com/propublica/django-collaborative/issues/57 and that should be fixed now.
