### ISSUE TITLE
Can't Re-Import Google Sheet Response

### ISSUE THREAD

**Issue by maya-miller-engagement** [propublica/django-collaborative#65]
Hi Brandon,

Maya here -- hope you're doing well. I'm trying to re-import the Google sheet attached to "Longtermcare ctp" data source, and am getting a Server Error (500). Could you help de-bug?

Thanks,

Maya

**Comment by brandonrobertz** [comment]
You're getting an error when you re-import it, but it imported fine initially?

**Comment by maya-miller-engagement** [comment]
Hey Brandon,

That's right. Happy to jump on a call if you'd like. I'm at (646) 241-8253.

Thanks,

Maya
________________________________

**Comment by brandonrobertz** [comment]
I'm not able to replicate the bug by importing and re-importing.

Some questions:
- If you import the sheet fresh and then immediately re-import it, do you get a crash still?
- Did the headers change at any point?
- Do you have any column data types set?

**Comment by brandonrobertz** [comment]
Closing this as it turned out to not be a collaborate bug --- but error handling needs to be more user friendly.
