### ISSUE TITLE
Private Google Spreadsheet error

### ISSUE THREAD

**Issue by rachelgli** [propublica/django-collaborative#7]
![Screen Shot 2019-06-19 at 11 09 04 AM](https://user-images.githubusercontent.com/42387717/59777764-39d2d400-9283-11e9-9c8a-043455f813e1.png)
This is the screen that appears after I authorize the app and input the three fields.

**Comment by brandonrobertz** [comment]
Fixed. Was missing an import for a multi-lingual error message.
