### ISSUE TITLE
Private Google Spreadsheet error #2

### ISSUE THREAD

**Issue by rachelgli** [propublica/django-collaborative#8]
![Screen Shot 2019-06-24 at 3 48 13 PM](https://user-images.githubusercontent.com/42387717/60048382-0389c000-969a-11e9-8e23-6bbe3a2172d3.png)
Got an error when I tried to upload a private spreadsheet. Three columns; one column has a bunch of blank cells.

**Comment by brandonrobertz** [comment]
This was from a duplicate/blank column in the source spreadsheet. This is fixed
